<a href="https://colab.research.google.com/github/chsrinidh/AIML-Lab/blob/main/aiml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
a=[1,2,3,4,5,6]
print("this the list",a)
array=np.array(a)
print("this the array",array)

this the list [1, 2, 3, 4, 5, 6]
this the array [1 2 3 4 5 6]


In [ ]:
print(type(a))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
result_mul_array = array * 2
print( result_mul_array)
result_div_array = array / 2
print( result_div_array)
result_pow_array = array ** 2
print( result_pow_array)

[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]
[ 1  4  9 16 25 36]


In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = array1 + array2
print(result)

[5 7 9]


In [ ]:
sin_result = np.sin(array)
print( sin_result)
log_result = np.log(array)
print(log_result)
log2_result = np.log2(array)
print(log2_result)
exp_result = np.exp(array)
print(exp_result)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[0.         1.         1.5849625  2.         2.32192809 2.5849625 ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
